In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [11]:
import torch

In [2]:

a = np.ones((1, 1, 5, 5))
b = np.ones((1, 1, 5, 5))
np.stack([a, b]).mean(0).shape

(1, 1, 5, 5)

In [38]:
a = torch.ones((5,5), requires_grad=True).float()
b = torch.zeros((5,5), requires_grad=True).float()
z = torch.Tensor(np.ones((5,5))*0.5).float()
z.requires_grad = True
with torch.no_grad():
    pass
    f = z*a
loss = (((f - b) ** 2).sum()) ** 0.5
loss.backward()
b.grad

tensor([[-0.2000, -0.2000, -0.2000, -0.2000, -0.2000],
        [-0.2000, -0.2000, -0.2000, -0.2000, -0.2000],
        [-0.2000, -0.2000, -0.2000, -0.2000, -0.2000],
        [-0.2000, -0.2000, -0.2000, -0.2000, -0.2000],
        [-0.2000, -0.2000, -0.2000, -0.2000, -0.2000]])

In [71]:
thresh_list = np.arange(0.3, 0.9999, 0.05)
min_area_list = np.arange(0, 7000, 100)
len(thresh_list) * len(min_area_list) * 5/60/60

1.3611111111111112

In [72]:
def base(data):
    sample_data = data
    sample_data = sample_data[(np.abs(sample_data[:, 0] - 0.5) < 0.2)]
    print(data[:, 0].min())
    print("#", sample_data[np.argmin(sample_data[:, 1])])
    print("#", sample_data[np.argmax(sample_data[:, 2])])
    print("#", sample_data[np.argmax(sample_data[:, -1])])

In [73]:
np.load("new_thresholds/second_accum_bug_find_threshold_dump.npy").shape

(50, 5)

In [74]:
data.shape

(770, 5)

In [75]:
path = "new_thresholds/accum_bug_find_threshold_dump.npy"
data = np.load(path)#.astype(np.float)
data = np.vstack([data, np.load("new_thresholds/second_accum_bug_find_threshold_dump.npy")])
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])
base(data)

2 [5.0000000e-01 3.6000000e+03 8.5525632e-01 9.6666664e-01 4.3965471e-01]
3 [9.4999999e-01 6.9000000e+03 8.2483280e-01 9.9333334e-01 1.9626354e-01]
4 [3.0000001e-01 8.0000000e+02 7.0570523e-01 7.5666666e-01 5.1560020e-01]
0.2
# [0.3        0.         0.6133206  0.64       0.51379657]
# [5.0000000e-01 3.6000000e+03 8.5525632e-01 9.6666664e-01 4.3965471e-01]
# [3.0000001e-01 8.0000000e+02 7.0570523e-01 7.5666666e-01 5.1560020e-01]


In [76]:
path = "new_thresholds/alignaug_find_threshold_dump.npy"
data = np.load(path)#.astype(np.float)
data = np.vstack([data, np.load("new_thresholds/second_alignaug_find_threshold_dump.npy")])
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])
base(data)

2 [5.0000000e-01 4.5000000e+03 8.4668142e-01 9.7000003e-01 3.8665766e-01]
3 [9.4999999e-01 4.8000000e+03 8.2833511e-01 9.9333334e-01 2.1283092e-01]
4 [0.25       0.         0.61733246 0.6433333  0.52033967]
0.2
# [0.3        0.         0.63038874 0.66       0.51992774]
# [5.0000000e-01 4.5000000e+03 8.4668142e-01 9.7000003e-01 3.8665766e-01]
# [0.3        0.         0.63038874 0.66       0.51992774]


In [77]:
path = "new_thresholds/alignaug_div_find_threshold_dump.npy"
data = np.load(path)#.astype(np.float)
data = np.vstack([data, np.load("new_thresholds/second_alignaug_div_find_threshold_dump.npy")])
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])
base(data)

2 [5.5000001e-01 3.3000000e+03 8.5972995e-01 9.7666669e-01 4.2351285e-01]
3 [9.4999999e-01 5.4000000e+03 8.2801992e-01 9.9333334e-01 2.1133976e-01]
4 [0.25       0.         0.6867709  0.73333335 0.51307595]
0.2
# [0.3        0.         0.6999138  0.75       0.51307374]
# [5.5000001e-01 3.3000000e+03 8.5972995e-01 9.7666669e-01 4.2351285e-01]
# [0.3        0.         0.6999138  0.75       0.51307374]


In [48]:
# alignaug_dice_find_threshold_dump.npy
data = np.load("thresholds/alignaug_1024_find_threshold_dump.npy")#.astype(np.float)
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])
base(data)
data = np.load("thresholds/2alignaug_1024_find_threshold_dump.npy")#.astype(np.float)
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])
base(data)
data = np.load("thresholds/alignaug_dice_find_threshold_dump.npy")#.astype(np.float)
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])
base(data)

2 [8.0000001e-01 3.3000000e+03 8.5246569e-01 9.7000003e-01 4.1401944e-01]
3 [9.4999999e-01 5.9000000e+03 8.3098692e-01 9.9333334e-01 2.2537483e-01]
4 [  0.45       200.           0.7712117    0.8433333    0.50217134]
0.45
# [  0.45       100.           0.75542957   0.8233333    0.50212336]
# [5.0000000e-01 4.2000000e+03 8.4916764e-01 9.6333331e-01 4.2328748e-01]
# [  0.45       200.           0.7712117    0.8433333    0.50217134]
2 [8.3999997e-01 2.9000000e+03 8.5377705e-01 9.7000003e-01 4.2022252e-01]
3 [9.9000001e-01 7.9000000e+03 8.0619216e-01 9.9666667e-01 9.5651962e-02]
4 [  0.35       100.           0.7403919    0.80333334   0.5055972 ]
0.35
# [  0.4        100.           0.7479002    0.81333333   0.5038105 ]
# [5.600000e-01 3.900000e+03 8.494341e-01 9.633333e-01 4.245477e-01]
# [  0.4        100.           0.7479002    0.81333333   0.5038105 ]
2 [8.5000002e-01 2.3000000e+03 8.5848415e-01 9.8000002e-01 4.0518522e-01]
3 [9.4999999e-01 7.9000000e+03 8.1859720e-01 9.9333334e-01 1.66

In [50]:
data = np.load("thresholds/alignaug_div_find_threshold_dump.npy")#.astype(np.float)
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])
base(data)
data = np.load("thresholds/2alignaug_div_find_threshold_dump.npy")#.astype(np.float)
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])
base(data)
data = np.load("thresholds/alignaug_div_dice_find_threshold_dump.npy")#.astype(np.float)
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])
base(data)

2 [8.9999998e-01 1.4000000e+03 8.6554992e-01 9.8333335e-01 4.2617440e-01]
3 [9.4999999e-01 5.9000000e+03 8.3131796e-01 9.9000001e-01 2.3937537e-01]
4 [  0.45       100.           0.790468     0.8666667    0.50621873]
0.45
# [  0.45       100.           0.790468     0.8666667    0.50621873]
# [5.5000001e-01 4.9000000e+03 8.5929072e-01 9.8333335e-01 3.9656597e-01]
# [  0.45       100.           0.790468     0.8666667    0.50621873]
2 [8.8999999e-01 1.6000000e+03 8.6596197e-01 9.8333335e-01 4.2812347e-01]
3 [9.9000001e-01 7.9000000e+03 8.0842149e-01 9.9333334e-01 1.1863221e-01]
4 [  0.35       100.           0.78819346   0.86333334   0.5078941 ]
0.35
# [  0.4        100.           0.7906883    0.8666667    0.50726074]
# [5.6999999e-01 2.7000000e+03 8.5956872e-01 9.6666664e-01 4.6005398e-01]
# [  0.4        100.           0.7906883    0.8666667    0.50726074]
2 [7.5000000e-01 1.9000000e+03 8.6403471e-01 9.8333335e-01 4.1900679e-01]
3 [9.4999999e-01 7.9000000e+03 8.1847686e-01 9.9333334e-01

In [51]:
data = np.load("thresholds/bugged_accum_find_threshold_dump.npy")#.astype(np.float)
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])
base(data)
data = np.load("thresholds/accum_bug_tta_find_threshold_dump.npy")#.astype(np.float)
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])
base(data)

2 [8.9999998e-01 3.8000000e+03 8.6259234e-01 9.9000001e-01 3.8731489e-01]
3 [9.7500002e-01 5.9000000e+03 8.3164948e-01 9.9000001e-01 2.4094373e-01]
4 [  0.15       100.           0.64782196   0.68666667   0.50291693]
0.15
# [  0.4        100.           0.7041272    0.76         0.49570107]
# [5.250000e-01 4.900000e+03 8.546827e-01 9.766667e-01 3.996374e-01]
# [  0.4        100.           0.7041272    0.76         0.49570107]
2 [5.0000000e-01 5.4000000e+03 8.5559183e-01 9.8666668e-01 3.6663425e-01]
3 [9.4999999e-01 6.9000000e+03 8.2444835e-01 9.9333334e-01 1.9444513e-01]
4 [4.0000001e-01 1.0000000e+03 7.3908967e-01 8.0000001e-01 5.1187181e-01]
0.4
# [4.0000001e-01 1.0000000e+03 7.3908967e-01 8.0000001e-01 5.1187181e-01]
# [5.0000000e-01 5.4000000e+03 8.5559183e-01 9.8666668e-01 3.6663425e-01]
# [4.0000001e-01 1.0000000e+03 7.3908967e-01 8.0000001e-01 5.1187181e-01]


In [ ]:
data = np.load("thresholds/alignaug_div_dice_find_threshold_dump.npy")#.astype(np.float)


In [ ]:
len(data)

In [ ]:
thresh_list = np.arange(0.35, 0.9999, 0.01)
min_area_list = np.arange(100, 8000, 100)
len(thresh_list) * len(min_area_list) * 3 / 60 / 60

In [ ]:
sample_data = data
sample_data = sample_data[(np.abs(sample_data[:, 0] - 0.5) < 0.00001)]
sample_data = sample_data[(np.abs(sample_data[:, 1] - 3000) < 0.00001)]
sample_data

In [ ]:
sample_data = data
sample_data = sample_data[(np.abs(sample_data[:, 0] - 0.5) < 0.00001)]
print(sample_data[np.argsort(sample_data[:, 2])[:-5:-1]])
plt.plot(sample_data[:, 1], sample_data[:, 2], label="dice")
plt.plot(sample_data[:, 1], sample_data[:, 3], label="dice_neg")
plt.plot(sample_data[:, 1], sample_data[:, 4], label="dice_pos")
plt.legend()

In [ ]:
sample = data[data[:, 2] > 0.86]
sample[np.argsort(sample[:, 3])[:-20:-1]]

In [ ]:
sample_data = data[(data[:, 3] - 0.9889999999999999999)>0.0000000000000000000001]
print(sample_data)
sample_data = sample_data[np.argsort(sample_data[:, 4])[::-1]]
print(sample_data)

In [ ]:
# data2 = data[data[:, 0] > 0.5]
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[::-1]][0])

In [ ]:
# data2 = data[data[:, 0] > 0.5]
for i in range(2, 5):
    print(i, data[np.argsort(data[:, i])[:-6:-1]])

In [ ]:
pred = 0.77714 * data[:, 3] + (1 - 0.77714) * data[:, 4]

In [ ]:
pred[np.argsort(pred)[::-1]][:15].tolist()

In [ ]:
data[np.argsort(pred)[::-1]][:15, [0, 1, 3, 4]].tolist()

In [ ]:
# was_threshold = 0.336101
# should_be = 0.8278
def results(was_threshold, k, should_be, min_area, old_k=0.7886):
    f_data = data[(data[:, 1] == min_area)]
    index = np.argmin(np.abs(f_data[:, 0] - was_threshold))
    old_kaggle = f_data[index, 2]
    pos_val = f_data[index, 4]
    neg_val = f_data[index, 3]
    kaggle_score = k * neg_val + (1 - k) * pos_val
    print("Was threshold\t", was_threshold)
    print("Was min_area\t", min_area)
    print("Pos/Neg val\t", pos_val, neg_val)
    print("score old/new\t", old_kaggle, kaggle_score)
    special_data_x = []
    special_data_y = []
    for val in np.arange(0.10000, 0.99999, 0.000001):
        special_data_x.append(val)
        special_data_y.append(neg_val * val + (1-val)*pos_val)

    should_index = np.argmin(np.abs(np.array(special_data_y) - should_be))
    print("Old/new k\t", old_k, k)
    print("\t\t", special_data_x[should_index],special_data_y[should_index])
# fig = plt.figure()
# plt.plot(special_data_x, special_data_y), plt.show()

results(0.5, 0.77714, 0.8351, 3500)
print("###")
results(0.336101, 0.77714, 0.8278, 3500)
print("###")
results(0.6000000238418579, 0.77714, 0.8291, 3100, )


In [ ]:
len(np.arange(100, 6000, 100))

In [ ]:
len(np.arange(0.1, 0.9999, 0.05))

In [ ]:
18*59

In [ ]:
5*(59*18)/60.0/60.0

In [ ]:
%matplotlib notebook
colors = ["blue", "red", "green"]
labels = ["dice", "dice_neg", "dice_pos"]
indeces = [2, 3]
for i in indeces:
    plt.plot(data[:, 0], data[:, i], c=colors[i-1], label=labels[i-1])
plt.legend()
# plt.xticks(data[:, 0][::12].round(2));

In [ ]:
%matplotlib notebook
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
sample = data
ax = fig.add_subplot(111, projection='3d')
ax.scatter(sample[:, 0], sample[:, 1], sample[:, 2], c=sample[:, 2])


In [ ]:
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
sample = data
ax = fig.add_subplot(111, projection='3d')
ax.scatter(sample[:, 0], sample[:, 1], sample[:, 3], c=sample[:, 3])

In [ ]:
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
sample = data
ax = fig.add_subplot(111, projection='3d')
ax.scatter(sample[:, 0], sample[:, 1], sample[:, 4], c=sample[:, 4])

In [ ]:
thresh_list = np.arange(0.45, 0.9999, 0.025)
min_area_list = np.arange(1500, 2500, 100)
len(thresh_list) * len(min_area_list) * 3/60.0

In [ ]:
thresh_list = np.arange(0.45, 0.9999, 0.025)
min_area_list = np.arange(2500, 6000, 100)
len(thresh_list) * len(min_area_list)

In [ ]:
770*3/60.0

In [ ]:
neg_path = "thresholds/submission_smp_unet_sampler_1024_95_5900.csv"
pos_path = "thresholds/submission_smp_unet_sampler_1024_40_1500.csv"
neg_df = pd.read_csv(neg_path)
pos_df = pd.read_csv(pos_path)
neg_df = neg_df[neg_df.EncodedPixels == " -1"]
print(neg_df.shape)
print(pos_df.shape)

In [ ]:
len(pos_df.ImageId.unique())

In [ ]:
pos_df.ImageId.isin(neg_df.ImageId).sum()

In [ ]:
pos_df[pos_df.ImageId.isin(neg_df.ImageId)]["EncodedPixels"] = " -1"
print((pos_df.ImageId == " -1").sum())

In [ ]:
len(pos_df.ImageId.unique())

In [ ]:
pos_df.to_csv("thresholds/combines.csv", index=None)

In [ ]:
pos_df.shape